### ISSUE TITLE
Another PED issue

### ISSUE THREAD

**Issue by damithc** [AY1920S1-CS2103-T11-2/main#186]
https://github.com/chowyiwai/ped/issues/21

**Comment by SendorasLeft** [comment]
thanks!

**Comment by SendorasLeft** [comment]
fixed in PR #196. The style for selected ExpandedCards will now be suppressed, since they're implicitly already the centre of focus in the list if they're expanded and the only one showing. Normal display Cards will remained unchanged.

On a side note, cards may be de-selected by `Ctrl+Primary Mouse Click` as per the default JavaFX behaviour.
