### ISSUE TITLE
More PED issues

### ISSUE THREAD

**Issue by damithc** [AY1920S1-CS2103-T11-2/main#187]
https://github.com/Dandford/ped/issues/8
https://github.com/Dandford/ped/issues/9
https://github.com/Dandford/ped/issues/10
https://github.com/Dandford/ped/issues/11
https://github.com/Dandford/ped/issues/12
https://github.com/Dandford/ped/issues/13
https://github.com/Dandford/ped/issues/14

**Comment by SendorasLeft** [comment]
Note: I'm not quite sure why, but I think this person was testing on the entirely wrong version (not `1.3` or `1.3.1`)

**Comment by SendorasLeft** [comment]
- ped8 will arrive in v2.0. even in v1.4, the functionality is already fulfilled exactly by the `find` command (which is mentioned in both the error message/user guide). on the more practical side, due to the limitations of grading for this module, we want to avoid too many repeat/similar functionalities for v1.4 between features as well, so that we each can focus more on the more unique aspects of our own features. this is especially so if the functionality already exists in `find`.
- ped9 has been resolved
- ped10 isn't a bug. if you would like to suggest an enhancement for 1.4 or 2.0, please place it under the `enhancements` tag.
- ped11, ped12, ped13: you seem to be on the wrong version of the userguide, or application, or both.
- ped14: again, you seem to be on the wrong version. however, in lieu of other ped feedback, `list` now strictly raises an error for invalid parameters instead of ignoring them, since many people seem to think that ignoring invalid parameters is a bug.
